#
# An auto defined `clippy` feature was introduced,
# but it was found to clash with user defined features,
# so was renamed to `cargo-clippy`.
#
# If you want standard clippy run:
# RUSTFLAGS= cargo clippy
[target.'cfg(feature = "cargo-clippy")']
rustflags = [
  "-Aclippy::all",
  "-Dclippy::correctness",
  "-Aclippy::if-same-then-else",
  "-Aclippy::clone-double-ref",
  "-Dclippy::complexity",
  "-Aclippy::zero-prefixed-literal",     # 00_1000_000
  "-Aclippy::type_complexity",           # raison d'etre
  "-Aclippy::nonminimal-bool",           # maybe
  "-Aclippy::borrowed-box",              # Reasonable to fix this one
  "-Aclippy::too-many-arguments",        # (Turning this on would lead to)
  "-Aclippy::unnecessary_cast",          # Types may change
  "-Aclippy::identity-op",               # One case where we do 0 +
  "-Aclippy::useless_conversion",        # Types may change
  "-Aclippy::unit_arg",                  # styalistic.
  "-Aclippy::option-map-unit-fn",        # styalistic
  "-Aclippy::bind_instead_of_map",       # styalistic
  "-Aclippy::erasing_op",                # E.g. 0 * DOLLARS
  "-Aclippy::eq_op",                     # In tests we test equality.
  "-Aclippy::while_immutable_condition", # false positives
  "-Aclippy::needless_option_as_deref",  # false positives
  "-Aclippy::derivable_impls",           # false positives
  "-Aclippy::stable_sort_primitive",     # prefer stable sort
  "-Aclippy::extra-unused-type-parameters", # stylistic
]

[env]
# The version of the node.
#
# This is the version that is used for versioning this node binary.
# By default the `minor` version is bumped in every release. `Major` or `patch` releases are only
# expected in very rare cases.
#
# The worker binaries associated to the node binary should ensure that they are using the same
# version as the main node that started them.
POLKADOT_NODE_VERSION = "1.1.0"
